### ISSUE TITLE
centralize state within DCPTools Rhino plugin

### ISSUE THREAD

**Issue by carstoid** [NYCPlanning/ud-digital-practice#12]
previous treatment of application state is super messy:
- multiple/overlapping input shapefiles (blocks, lots, soft sites)
- input/output combined into same excel spreadsheet
- state stored in excel/rhino isn't accessible to outside project team members
- grasshopper script modifies itself?
- grasshopper script control panel can save/restore "configuration" (unclear what this is, current UI state of control panel itself?)
- this complicates the use of the script and any associated coordination between teams (unclear where or how things are documented and who should/can modify what)
- also makes debugging difficult

## Discussion & Proposed Solutions

![IMG_0058](https://user-images.githubusercontent.com/19612711/73768521-28253a80-4747-11ea-851a-555f258ea07c.jpg)

Ideally, we'd use a model like one shown above where application state is read/written from and persisted in a **single location**, in this case the Rhino model itself. The Grasshopper script and associated UI layer should provide a view onto this state but be stateless in themselves. Inputs should modify state in a single operation and then become unnecessary. Outputs should be able to capture select parts of the state at a given moment in time and copy them to a separate file or data structure. We've also discussed the possibility of using a cloud-based platform to make app state visible to project stakeholders while the project is underway, this would need to be periodically updated to reflect app state in a one-way manner.

- [x] export handling rewrite #90 
- [x] consolidate state variables in one place in script #91
- [x] grasshopper & associated UI should be  completely stateless.
- [x] above is reflected in the new release process, still needs to be documented (#92)
- [ ] explore use of widely accessible, cloud-based spreadsheet/database (airtable?) should store as much state as possible to maintain visibility across project team (see #31)
- [x] initial state should be generated on initial startup by the grasshopper script (doesn't require a rhino or excel template) #93
- [x] decouple state from input spreadsheet and shapefiles. this has multiple parts:
  - treat spatial data interface as a strict *import* rather than as a linked file where project state is stored partly in the dataset's attributes (this is how site ID process happens now) #94
  - treat zoning assumptions as strict import with interface within script to update via subsequent overwriting import operations #95
  - treat "site specific assumptions" as above (same issue)

**Comment by carstoid** [comment]
for data persistence – see: https://discourse.mcneel.com/t/serializing-non-rhino-classes-to-a-rhino-file/5499

lower in the thread, the TestMarkus example provides what looks like an OK example of how you would implement this in the plugin. In the example, there is a data container class "TestMarkusData", with a single "Value" property, and Write and Read methods for serializing to RhinoCommon's BinaryArchiveReader.

The same file also contains a second class "TestMarkusDataTable" which is a list of "TestMarkusData". It provides its own methods for serializing/deserializing TestMarkusData objects.
